/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123Char125DotmdRouteImport } from './routes/{$}[.]md'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as HomelayoutRouteRouteImport } from './routes/_homelayout/route'
import { Route as HomelayoutIndexRouteImport } from './routes/_homelayout/index'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as HomelayoutSplatRouteImport } from './routes/_homelayout/$'

const Char123Char125DotmdRoute = Char123Char125DotmdRouteImport.update({
  id: '/{$}.md',
  path: '/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HomelayoutRouteRoute = HomelayoutRouteRouteImport.update({
  id: '/_homelayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomelayoutIndexRoute = HomelayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomelayoutRouteRoute,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HomelayoutSplatRoute = HomelayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => HomelayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomelayoutIndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/$': typeof HomelayoutSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/$': typeof HomelayoutSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/': typeof HomelayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homelayout': typeof HomelayoutRouteRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/_homelayout/$': typeof HomelayoutSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/_homelayout/': typeof HomelayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{$}.md'
    | '/$'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{$}.md'
    | '/$'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/'
  id:
    | '__root__'
    | '/_homelayout'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{$}.md'
    | '/_homelayout/$'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/_homelayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomelayoutRouteRoute: typeof HomelayoutRouteRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  Char123Char125DotmdRoute: typeof Char123Char125DotmdRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$}.md': {
      id: '/{$}.md'
      path: '/{$}.md'
      fullPath: '/{$}.md'
      preLoaderRoute: typeof Char123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homelayout': {
      id: '/_homelayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomelayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homelayout/': {
      id: '/_homelayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomelayoutIndexRouteImport
      parentRoute: typeof HomelayoutRouteRoute
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homelayout/$': {
      id: '/_homelayout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof HomelayoutSplatRouteImport
      parentRoute: typeof HomelayoutRouteRoute
    }
  }
}

interface HomelayoutRouteRouteChildren {
  HomelayoutSplatRoute: typeof HomelayoutSplatRoute
  HomelayoutIndexRoute: typeof HomelayoutIndexRoute
}

const HomelayoutRouteRouteChildren: HomelayoutRouteRouteChildren = {
  HomelayoutSplatRoute: HomelayoutSplatRoute,
  HomelayoutIndexRoute: HomelayoutIndexRoute,
}

const HomelayoutRouteRouteWithChildren = HomelayoutRouteRoute._addFileChildren(
  HomelayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomelayoutRouteRoute: HomelayoutRouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  Char123Char125DotmdRoute: Char123Char125DotmdRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
