name: Docs Validation

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/validate-docs.yaml'

  pull_request:
    branches:
      - '*'
    paths:
      - 'docs/**'
      - '.github/workflows/validate-docs.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

      - name: Format code 
        run: pnpm format

      - name: Build docs
        run: pnpm build
